# Generated by Django 2.0.1 on 2018-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=40)),
                ('secret', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=256)),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('street_address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=20)),
            ],
        ),
    ]
