# Generated by Django 2.0.1 on 2018-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_person_isreal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
