# Generated by Django 2.0.1 on 2018-01-20 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='qdate',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='date submitted'),
        ),
    ]
